name: my_bluetooth
description: My Bluetooth - Connecting and transferring data to other devices using Bluetooth
version: 1.0.2
maintainer: Ducnguyen (Wong) and Thaodoan (Mia)
repository: https://github.com/ngmduc2012/my_bluetooth

environment:
  sdk: ^3.5.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.wongcoupon.my_bluetooth
        pluginClass: MyBluetooth
      ios:
        pluginClass: MyBluetooth

