name: my_bluetooth
description: My Bluetooth - Connecting and transferring data to other devices (printer) using Bluetooth
version: 1.0.2+3
maintainers:
  - "Ducnguyen (Wong) <ngmduc2012@gmail.com>"
repository: https://github.com/ngmduc2012/my_bluetooth

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.wongcoupon.my_bluetooth
        pluginClass: MyBluetooth
      ios:
        pluginClass: MyBluetooth

screenshots:
  - description: "avatar plugin"
    path: avatar.png

topics:
  - bluetooth
  - bluetooth-communication
  - device-connection
  - printer
  - flutter-plugin